# Generated by Django 2.1.5 on 2019-02-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('food_item', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('price', models.CharField(default='DEFAULT VALUE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('food_item', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('price', models.CharField(default='DEFAULT VALUE', max_length=30)),
            ],
        ),
    ]
