# Generated by Django 2.1.5 on 2019-02-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rincon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foods',
            new_name='Food',
        ),
    ]
