# Generated by Django 2.1.5 on 2019-02-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rincon', '0002_auto_20190212_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_item',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
    ]
